@startuml
skinparam linetype ortho
interface Subject {
  observers
  {method} RegisterObserver()
  {method} UnregisterObserver()
  {method} NotifyObservers()
}
interface Observer {
  {method} Update()
}
class ConcreteSubject {
  observers
  {method} RegisterObserver()
  {method} UnregisterObserver()
  {method} NotifyObservers()
}
class ConcreteObserver {
  {method} Update()
}

Subject o-right-> Observer: notifies
ConcreteSubject .up.|> Subject
ConcreteObserver .up.|> Observer
@enduml
