@startuml
class Flyweight {
  -intrinsicState: String
  +Operation(extrinsicState: String)
}

class FlyweightFactory {
  -flyweights: map<string, Flyweight>
  +GetFlyweight(key: string): Flyweight
}

class Client {}
hide Client circle 

Client --> Flyweight: Operation
Client --> FlyweightFactory: GetFlyweight
FlyweightFactory o-> Flyweight

@enduml
